# Generated by Django 5.0.2 on 2024-06-02 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_posts_title_alter_comment_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 10, 18, 22, 713018)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 10, 18, 22, 713018)),
        ),
    ]
