# Generated by Django 5.0.2 on 2024-06-10 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_comment_timestamp_alter_posts_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 21, 38, 37, 850719)),
        ),
    ]
