# Generated by Django 5.0.2 on 2024-06-10 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_posts_number_of_ratings_posts_total_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='number_of_ratings',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='total_rating',
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 21, 44, 49, 501998)),
        ),
    ]
