# Generated by Django 5.0.2 on 2024-06-10 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_comment_timestamp_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 22, 29, 8, 53403)),
        ),
    ]
