# Generated by Django 5.0.2 on 2024-06-10 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_comment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 22, 34, 33, 406164)),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
