# Generated by Django 5.0.2 on 2024-06-12 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_comment_timestamp_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 11, 52, 57, 876368)),
        ),
    ]
